- ParProcCo/job_controller.py
- ParProcCo/job_scheduler.py
- scripts/msm_cluster_submit
- scripts/p99_cluster_submit
- tests/test_job_controller.py
- tests/test_job_scheduler.py
- tests/test_msm_cluster_submit.py
Add automatic selection of queue when testing
> Support clusters that need resources limits to be specified

- .gitignore
- ParProcCo/utils.py
- scripts/msm_cluster_submit
Add shorthand output option, make job argument optional and defaults to 1, use better way to get user, fix wrong usage of AnyStr, add underscore prefix for unused variable
> Minor fixes

- ParProcCo/utils.py
Replace usage of wrong environment variable with which. Also, refactor check_location. and tidy up some stray new lines in messages
> Replace get_absolute_path

- ParProcCo/job_controller.py
- ParProcCo/job_scheduler.py
- ParProcCo/utils.py
- scripts/msm_cluster_submit
- tests/test_job_scheduler.py
Also set attributes instead of passing same arguments through many calls, restrict cores argument to integers
> Revert removed method to fix broken resubmit method

- ParProcCo/job_controller.py
- ParProcCo/job_scheduler.py
- ParProcCo/msm_processing_mode_interface.py
- ParProcCo/simple_processing_mode_interface.py
- ParProcCo/utils.py
- scripts/msm_agg_jobscript
- scripts/msm_cluster_submit
- tests/test_job_scheduler.py
Simplify calculation of number jobs, correct argument help of aggregator
> Single job case

- ParProcCo/job_scheduler.py
- scripts/msm_cluster_runner
- tests/test_msm_cluster_submit.py
Also check if module is available before sourcing it
> Add support for TEST_PPC_DIR

- ParProcCo/aggregator_interface.py
- ParProcCo/job_controller.py
- ParProcCo/msm_processing_mode.py
- ParProcCo/nxdata_aggregation_mode.py
- ParProcCo/nxdata_aggregator.py
- example/simple_aggregation_mode.py
- example/simple_data_aggregator.py
- example/simple_processing_mode.py
- scripts/msm_cluster_submit
- scripts/nxdata_aggregate
- tests/test_job_controller.py
- tests/test_job_scheduler.py
- tests/test_msm_cluster_submit.py
- tests/test_nxdata_aggregator.py
- tests/test_simple_data_aggregator.py
- tests/utils.py
Rename files and classes, move simple ones into an example package, and remove duplicate cluster runner argument. Also check aggregator path exists, remove unused function in test script, change aggregator job name
> Big re-organisation of code

- ParProcCo/job_controller.py
- ParProcCo/job_scheduler.py
- ParProcCo/nxdata_aggregation_mode.py
- ParProcCo/passthru_processing_mode.py
- ParProcCo/program_wrapper.py
- ParProcCo/utils.py
- scripts/msm_cluster_submit
- tests/test_job_controller.py
- tests/test_job_scheduler.py
- tests/utils.py
Refactor to pass fewer arguments, reduce attributes, encapsulate program specific slicer and modes, update tests, and update deprecated equals calls
> Add pass thru mode

- ParProcCo/job_controller.py
- ParProcCo/job_scheduler.py
- ParProcCo/passthru_wrapper.py
- ParProcCo/program_wrapper.py
Also add missing program path in pass thru wrapper
> Fix pass-thru case where no output has been given

- ParProcCo/job_controller.py
- ParProcCo/job_scheduler.py
- ParProcCo/nxdata_aggregation_mode.py
- ParProcCo/passthru_wrapper.py
- ParProcCo/program_wrapper.py
- ParProcCo/scheduler_mode_interface.py
- ParProcCo/simple_data_slicer.py
- ParProcCo/slicer_interface.py
- example/simple_aggregation_mode.py
- example/simple_processing_mode.py
Also support slice, program_path as None, and remove unnecessary stack
trace logging
> Support output as None

- ParProcCo/job_controller.py
- ParProcCo/job_scheduler.py
- ParProcCo/nxdata_aggregation_mode.py
- ParProcCo/nxdata_aggregator.py
- ParProcCo/passthru_wrapper.py
- ParProcCo/program_wrapper.py
- ParProcCo/scheduler_mode_interface.py
- ParProcCo/utils.py
- scripts/nxdata_aggregate
- scripts/ppc_cluster_submit
- tests/test_job_controller.py
- tests/test_job_scheduler.py
- tests/test_nxdata_aggregator.py
- tests/test_simple_data_aggregator.py
- tests/test_simple_data_slicer.py
Adds logging statments and checks error and warning level logging in tests. Reduces long line lengths.
> Add logging

- ParProcCo/nxdata_aggregator.py
> Show time taken in NXdata aggregate in total seconds to millisecond

- ParProcCo/nxdata_aggregator.py
- tests/test_nxdata_aggregator.py
Copy process entries for sliced files into old_processed group in aggregation file
Check these groups are created in nx_aggregation test
> Copy old process entries into aggregated file and add test for this

- ParProcCo/job_scheduler.py
- tests/test_job_scheduler.py
Sometimes jobs are not terminated despite having finished so check status every 2 minutes
> Check jobs regularly

- .github/workflows/python-package.yml
- ParProcCo/job_controller.py
- ParProcCo/job_scheduler.py
- tests/test_job_controller.py
- tests/test_job_scheduler.py
- tests/test_nxdata_aggregator.py
- tests/utils.py
Setup GitHub workflow. Run tests for pull requests, excluding tests that require cluster runs.
> Add workflow

- ParProcCo/utils.py
- scripts/ppc_cluster_submit
This allows simpler installation without using a package
> Add back old config based wrapper

- ParProcCo/utils.py
- README.md
- setup.py
Document entry point, remove entry point for rs_map, refactor wrapper function
> Minor tidy up

- ParProcCo/job_scheduler.py
- ParProcCo/utils.py
- README.md
- scripts/ppc_cluster_runner
- setup.py
Also add missing bang to shebang
> Make working directory use cluster output if former is unspecified then home as fallback

- ParProcCo/job_controller.py
- ParProcCo/nxdata_aggregation_mode.py
- ParProcCo/passthru_wrapper.py
- ParProcCo/scheduler_mode_interface.py
- ParProcCo/utils.py
- example/simple_aggregation_mode.py
- example/simple_processing_mode.py
- tests/test_job_controller.py
Also add and correct some type annotations
> Add timestamp to aggregator output file name

- tests/test_job_controller.py
- tests/test_job_scheduler.py
- tests/test_nxdata_aggregator.py
- tests/test_simple_data_aggregator.py
- tests/utils.py
Also reduce excessive permissions
> Add a custom temporary directory class to aid debugging tests

- .gitignore
- ParProcCo/program_wrapper.py
Also generalize git ignoring cache directories
> Fix missing environment variable bug

- scripts/ppc_cluster_submit
Also check for script and arguments
> Fix time parsing with missing conversion

- ParProcCo/nxdata_aggregation_mode.py
- ParProcCo/passthru_wrapper.py
- ParProcCo/program_wrapper.py
- ParProcCo/scheduler_mode_interface.py
- ParProcCo/utils.py
- example/simple_aggregation_mode.py
- example/simple_processing_mode.py
- tests/test_job_controller.py
Replace script path with script name and search on PATH for script
> Search for scripts on PATH

- ParProcCo/job_controller.py
- ParProcCo/job_scheduler.py
- ParProcCo/utils.py
- README.md
- scripts/ppc_cluster_submit
- tests/test_job_scheduler.py
Add extra property environments that allow Slurm's fields in job properties to be set from environment variables
> Remove cluster config

- ParProcCo/job_controller.py
- ParProcCo/job_scheduler.py
- ParProcCo/utils.py
- scripts/ppc_cluster_submit
Use an internal constant, make job scheduler's REST methods internal and consistent, and strip any newlines from token
> Remove Slurm version argument

- ParProcCo/job_controller.py
- scripts/ppc_cluster_submit
Also, set timeout for aggregation to scale with number of files
> Use a string to specify memory for ppc cluster submit

- .github/workflows/python-package.yml
- conda/meta.yaml
- dev_requirements.txt
- environment.yml
- setup.py
> Update dependency metadata

- .github/workflows/python-package.yml
- requirements.txt
- setup.py
Update requirements to match release and use requirements if dev requirements is absent
> Add missing long description

- .gitignore
- .vscode/create_env.sh
- .vscode/launch.json
- .vscode/settings.json
- .vscode/tasks.json
- README.md
I've been using this to make things easier (though it is also where I accidentally broke the key for a bit) and thought it might be helpful to share.
> Automate some environment handling with VSCode
